// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    var figure;
    figure = [[0, 0, 1, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 1, 0], [1, 0, 0, 1, 1, 0, 0, 1], [0, 0, 1, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 1, 0, 0], [1, 0, 0, 1, 1, 0, 0, 1], [0, 1, 0, 0, 0, 0, 1, 0], [0, 0, 1, 0, 0, 1, 0, 0]];
    figure = [[0, 1, 1, 0], [1, 0, 0, 1], [1, 0, 0, 1], [0, 1, 1, 0]];
    window.app = new Fractal('#fractal', figure);
    return app.draw(function() {
      return console.log('done');
    });
  });

}).call(this);
